databases:
  - name: 'postgres'
    host: 'aws-0-ap-northeast-1.pooler.supabase.com'
    database: 'postgres'
    username: 'postgres.jerjyllsawcvrgfqrnwr'
    password: <%= ENV['DATABASE_PASSWORD'] %>
    region: singapore
  # - name: 'good_daily_news_db'
  #   databaseName: 'news_a0wc'
  #   user: 'news_a0wc_user'
  #   region: singapore

services:
  - type: web
    name: 'good_daily_news'
    env: ruby
    region: singapore
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: 'news_a0wc'
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
