databases:
  - name: 'good-daily-news-db'
    databaseName: 'news_gfvm'
    user: 'good-daily-news'
    region: singapore

services:
  - type: web
    name: 'good-daily-news'
    env: ruby
    region: singapore
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 'good-daily-news-db'
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
